import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  QUOTE_ACCEPTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ACCEPTED_BY_EMAIL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ACCEPTED_BY_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_FILE_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_KIND_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_KIND_OPTION_CONTRACT_UNIVERSAL_IDENTIFIER,
  QUOTE_KIND_OPTION_QUOTE_UNIVERSAL_IDENTIFIER,
  QUOTE_KIND_CONTRACT,
  QUOTE_KIND_QUOTE,
  QUOTE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_OBJECT_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_DRAFT,
  QUOTE_STATUS_ACCEPTED,
  QUOTE_STATUS_DECLINED,
  QUOTE_STATUS_EXPIRED,
  QUOTE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_OPTION_ACCEPTED_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_OPTION_DECLINED_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_OPTION_EXPIRED_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_OPTION_SENT_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_SENT,
  QUOTE_SUBTOTAL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TAX_RATE_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TERMS_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TOTAL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_VALID_UNTIL_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

// Line items live on the related QuoteLine object (see quote-line.object.ts);
// the relation field itself is declared separately in
// src/fields/quote-quote-lines-relation.field.ts, following the same
// split-file pattern the document-generator example uses for its relations.
export default defineObject({
  universalIdentifier: QUOTE_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'quote',
  namePlural: 'quotes',
  labelSingular: 'Quote',
  labelPlural: 'Quotes',
  description:
    'A quote or contract sent to a customer, with line-item pricing, a generated PDF, and an acceptance record captured from a public link.',
  icon: 'IconFileInvoice',
  labelIdentifierFieldMetadataUniversalIdentifier:
    QUOTE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: QUOTE_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Quote or contract name, e.g. "Acme — annual plan".',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: QUOTE_KIND_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'kind',
      label: 'Kind',
      description: 'Whether this is a price quote or a contract to sign.',
      icon: 'IconCategory',
      defaultValue: `'${QUOTE_KIND_QUOTE}'`,
      options: [
        {
          id: QUOTE_KIND_OPTION_QUOTE_UNIVERSAL_IDENTIFIER,
          value: QUOTE_KIND_QUOTE,
          label: 'Quote',
          color: 'blue',
          position: 0,
        },
        {
          id: QUOTE_KIND_OPTION_CONTRACT_UNIVERSAL_IDENTIFIER,
          value: QUOTE_KIND_CONTRACT,
          label: 'Contract',
          color: 'purple',
          position: 1,
        },
      ],
    },
    {
      universalIdentifier: QUOTE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Where this quote/contract is in its lifecycle.',
      icon: 'IconProgress',
      defaultValue: `'${QUOTE_STATUS_DRAFT}'`,
      options: [
        {
          id: QUOTE_STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
          value: QUOTE_STATUS_DRAFT,
          label: 'Draft',
          color: 'gray',
          position: 0,
        },
        {
          id: QUOTE_STATUS_OPTION_SENT_UNIVERSAL_IDENTIFIER,
          value: QUOTE_STATUS_SENT,
          label: 'Sent',
          color: 'blue',
          position: 1,
        },
        {
          id: QUOTE_STATUS_OPTION_ACCEPTED_UNIVERSAL_IDENTIFIER,
          value: QUOTE_STATUS_ACCEPTED,
          label: 'Accepted',
          color: 'green',
          position: 2,
        },
        {
          id: QUOTE_STATUS_OPTION_DECLINED_UNIVERSAL_IDENTIFIER,
          value: QUOTE_STATUS_DECLINED,
          label: 'Declined',
          color: 'red',
          position: 3,
        },
        {
          id: QUOTE_STATUS_OPTION_EXPIRED_UNIVERSAL_IDENTIFIER,
          value: QUOTE_STATUS_EXPIRED,
          label: 'Expired',
          color: 'yellow',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier: QUOTE_VALID_UNTIL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'validUntil',
      label: 'Valid until',
      description: 'The quote/contract expires after this date.',
      icon: 'IconCalendarDue',
    },
    {
      universalIdentifier: QUOTE_TERMS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.RICH_TEXT,
      name: 'terms',
      label: 'Terms',
      description:
        'Contract terms or quote notes, rendered above the line items on the generated PDF.',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: QUOTE_SUBTOTAL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'subtotal',
      label: 'Subtotal',
      description: 'Sum of all line item totals, before tax. Computed when the PDF is generated.',
      icon: 'IconSum',
    },
    {
      universalIdentifier: QUOTE_TAX_RATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'taxRate',
      label: 'Tax rate (%)',
      description: 'Tax percentage applied to the subtotal, e.g. 16 for 16%.',
      icon: 'IconPercentage',
    },
    {
      universalIdentifier: QUOTE_TOTAL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'total',
      label: 'Total',
      description: 'Subtotal plus tax. Computed when the PDF is generated.',
      icon: 'IconSum',
    },
    {
      universalIdentifier: QUOTE_FILE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'file',
      label: 'File',
      description: 'The generated quote/contract as a downloadable PDF.',
      icon: 'IconFileTypePdf',
      universalSettings: { maxNumberOfValues: 1 },
    },
    {
      universalIdentifier: QUOTE_ACCEPTED_BY_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'acceptedByName',
      label: 'Accepted by (name)',
      description:
        'Name typed by the customer on the public acceptance page. Not a cryptographic signature — see design doc for the tradeoff.',
      icon: 'IconSignature',
    },
    {
      universalIdentifier: QUOTE_ACCEPTED_BY_EMAIL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'acceptedByEmail',
      label: 'Accepted by (email)',
      description: 'Email typed by the customer on the public acceptance page.',
      icon: 'IconMail',
    },
    {
      universalIdentifier: QUOTE_ACCEPTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE_TIME,
      name: 'acceptedAt',
      label: 'Accepted at',
      description: 'When the customer accepted this quote/contract.',
      icon: 'IconCalendarCheck',
    },
  ],
});
